name: Publish Release

on:
  workflow_dispatch:
    inputs:
      mod:
        description: 'Which mod?'
        required: true
        type: choice
        options:
          - 'ZeCompatch TTS Upgrade All;3353474883'

jobs:
  release:
    name: "Publish Release"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Metadata
        id: metadata
        run: script/split-mod.sh "${{ inputs.mod }}"

      - name: Clean Repository
        run: |
          mkdir ../steam-release
          mv "${{ steps.metadata.outputs.mod-name }}/STEAM_PAGE.bbcode" ../steam-release/STEAM_PAGE.bbcode
          rm -f "${{ steps.metadata.outputs.mod-name }}/vic3-tiger.conf"
          rm -f "${{ steps.metadata.outputs.mod-name }}/design_notes.txt"

        # Create mod metadata for the steam release
        # Uses STEAM_PAGE.bbcode to update steam description
        # Report: Generated metadata
      - name: Create Workshop Metadata
        id: steam-metadata
        shell: bash
        run: |
          ./script/create-release-vdf.sh "${{ github.workspace }}/${{ steps.metadata.outputs.mod-name }}" ../steam-release/STEAM_PAGE.bbcode "${{ steps.metadata.outputs.mod-id }}"
          mv workshop.vdf ../steam-release/workshop.vdf
          echo "vdf=$(realpath ../steam-release/workshop.vdf)" >> "$GITHUB_OUTPUT"
          echo "# Workflow Metadata" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat < ../steam-release/workshop.vdf)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Setup SteamCMD
        uses: buildalon/setup-steamcmd@v1.0.4

        # Publish to steam workshop
        # Uses generated metadata and configured workshop user
      - name: Publish to Workshop
        shell: bash
        run: |
          steamcmd +login ${{ secrets.WORKSHOP_USERNAME }} ${{ secrets.WORKSHOP_PASSWORD }} +workshop_build_item ${{ steps.steam-metadata.outputs.vdf }} +quit
          rm -rf "$STEAM_CMD"
          rm -rf "$STEAM_DIR"
          rm -rf "$STEAM_TEMP"

